name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.14'
      - name: Install Package and Dependencies
        run: raco pkg install --auto --batch datastar/
      - name: Run Tests
        run: raco test datastar/tests